version: "3.8"

services:
  backend:
    build: .
    container_name: bike-share-backend
    working_dir: /app
    command: npm run dev:backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    build: .
    container_name: bike-share-frontend
    working_dir: /app
    command: npm run dev:frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
